# Generated by Django 2.2.7 on 2019-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('department', models.CharField(default='', max_length=40)),
                ('authid', models.CharField(default='', max_length=50)),
                ('question', models.CharField(default='', max_length=200)),
                ('answer', models.CharField(default='', max_length=200)),
                ('confirm', models.CharField(default=False, help_text='yes/no', max_length=5)),
                ('upvote', models.IntegerField(default=0)),
            ],
        ),
    ]
